namespace AITrainingArena.Domain.Enums;

/// <summary>
/// Role assigned to an agent in a battle via cryptographic coin flip.
/// </summary>
public enum BattleRole
{
    /// <summary>Generates multi-hop questions for the solver.</summary>
    Proposer,
    /// <summary>Answers questions generated by the proposer.</summary>
    Solver
}
