[application]
name = "ai-training-arena-frontend"
default_platform = "web"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "AI Training Arena"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[web.resource]
style = []
script = []
