namespace AITrainingArena.Domain.Entities;

/// <summary>
/// A multi-hop question generated by the proposer during a battle.
/// Difficulty scales with hop count and chain complexity.
/// </summary>
public class Question
{
    /// <summary>The question text presented to the solver.</summary>
    public string Text { get; set; } = string.Empty;

    /// <summary>Number of reasoning hops required to answer.</summary>
    public int HopCount { get; set; }

    /// <summary>The expected correct answer.</summary>
    public string ExpectedAnswer { get; set; } = string.Empty;

    /// <summary>Computed difficulty score based on hop count and complexity.</summary>
    public decimal DifficultyScore { get; set; }

    /// <summary>Chain of reasoning steps from initial document to answer.</summary>
    public List<string> HopChain { get; set; } = [];

    /// <summary>When this question was generated.</summary>
    public DateTime GeneratedAt { get; set; }
}
